
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-27T11:13:35-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "0ecb31badc4ecd5e0ad53e849d7724548abbbdbe",
 "version": "0+untagged.2.g0ecb31b.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
